// This file will be auto-generated by: npm run types:generate
// Hand-maintained until Supabase project is connected and migrations are run.
// Derived from: supabase/migrations/001_initial_schema.sql + 002_students_subject_duration.sql + 003_lessons_location.sql
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: '12'
  }
  public: {
    Tables: {
      tutors: {
        Row: {
          id: string
          name: string
          email: string
          business_name: string | null
          abn: string | null
          bsb: string | null
          account_number: string | null
          bank_name: string | null
          invoice_prefix: string
          timezone: string
          currency: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          name: string
          email: string
          business_name?: string | null
          abn?: string | null
          bsb?: string | null
          account_number?: string | null
          bank_name?: string | null
          invoice_prefix?: string
          timezone?: string
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string
          business_name?: string | null
          abn?: string | null
          bsb?: string | null
          account_number?: string | null
          bank_name?: string | null
          invoice_prefix?: string
          timezone?: string
          currency?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      students: {
        Row: {
          id: string
          tutor_id: string
          name: string
          parent_name: string | null
          parent_email: string | null
          parent_phone: string | null
          subject: string | null
          default_rate: number | null
          default_duration_minutes: number | null
          notes: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tutor_id: string
          name: string
          parent_name?: string | null
          parent_email?: string | null
          parent_phone?: string | null
          subject?: string | null
          default_rate?: number | null
          default_duration_minutes?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tutor_id?: string
          name?: string
          parent_name?: string | null
          parent_email?: string | null
          parent_phone?: string | null
          subject?: string | null
          default_rate?: number | null
          default_duration_minutes?: number | null
          notes?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'students_tutor_id_fkey'
            columns: ['tutor_id']
            isOneToOne: false
            referencedRelation: 'tutors'
            referencedColumns: ['id']
          }
        ]
      }
      lessons: {
        Row: {
          id: string
          tutor_id: string
          student_id: string
          scheduled_at: string
          duration_minutes: number
          rate: number
          status: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes: string | null
          location: string | null
          recurring_series_id: string | null
          invoice_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tutor_id: string
          student_id: string
          scheduled_at: string
          duration_minutes: number
          rate: number
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes?: string | null
          location?: string | null
          recurring_series_id?: string | null
          invoice_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tutor_id?: string
          student_id?: string
          scheduled_at?: string
          duration_minutes?: number
          rate?: number
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          notes?: string | null
          location?: string | null
          recurring_series_id?: string | null
          invoice_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'lessons_tutor_id_fkey'
            columns: ['tutor_id']
            isOneToOne: false
            referencedRelation: 'tutors'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'lessons_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'lessons_invoice_id_fkey'
            columns: ['invoice_id']
            isOneToOne: false
            referencedRelation: 'invoices'
            referencedColumns: ['id']
          }
        ]
      }
      invoices: {
        Row: {
          id: string
          tutor_id: string
          student_id: string
          invoice_number: string
          status: 'draft' | 'sent' | 'paid'
          issued_date: string | null
          due_date: string | null
          paid_date: string | null
          subtotal: number
          total: number
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tutor_id: string
          student_id: string
          invoice_number: string
          status?: 'draft' | 'sent' | 'paid'
          issued_date?: string | null
          due_date?: string | null
          paid_date?: string | null
          subtotal?: number
          total?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tutor_id?: string
          student_id?: string
          invoice_number?: string
          status?: 'draft' | 'sent' | 'paid'
          issued_date?: string | null
          due_date?: string | null
          paid_date?: string | null
          subtotal?: number
          total?: number
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'invoices_tutor_id_fkey'
            columns: ['tutor_id']
            isOneToOne: false
            referencedRelation: 'tutors'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invoices_student_id_fkey'
            columns: ['student_id']
            isOneToOne: false
            referencedRelation: 'students'
            referencedColumns: ['id']
          }
        ]
      }
      invoice_items: {
        Row: {
          id: string
          invoice_id: string
          tutor_id: string
          description: string
          quantity: number
          unit_price: number
          amount: number
          lesson_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          invoice_id: string
          tutor_id: string
          description: string
          quantity?: number
          unit_price: number
          amount: number
          lesson_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          invoice_id?: string
          tutor_id?: string
          description?: string
          quantity?: number
          unit_price?: number
          amount?: number
          lesson_id?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'invoice_items_invoice_id_fkey'
            columns: ['invoice_id']
            isOneToOne: false
            referencedRelation: 'invoices'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invoice_items_tutor_id_fkey'
            columns: ['tutor_id']
            isOneToOne: false
            referencedRelation: 'tutors'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'invoice_items_lesson_id_fkey'
            columns: ['lesson_id']
            isOneToOne: false
            referencedRelation: 'lessons'
            referencedColumns: ['id']
          }
        ]
      }
      receipts: {
        Row: {
          id: string
          tutor_id: string
          invoice_id: string
          receipt_number: string
          paid_at: string
          amount_paid: number
          payment_method: string | null
          created_at: string
        }
        Insert: {
          id?: string
          tutor_id: string
          invoice_id: string
          receipt_number: string
          paid_at: string
          amount_paid: number
          payment_method?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          tutor_id?: string
          invoice_id?: string
          receipt_number?: string
          paid_at?: string
          amount_paid?: number
          payment_method?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'receipts_tutor_id_fkey'
            columns: ['tutor_id']
            isOneToOne: false
            referencedRelation: 'tutors'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'receipts_invoice_id_fkey'
            columns: ['invoice_id']
            isOneToOne: false
            referencedRelation: 'invoices'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
